python /home/young/liuyixin/8.29/CAMC/train_ddpg.py --debug_test Fasle \
--job train \
--model resnet50 \
--dataset imagenet \
--lbound 0.2 \
--rbound 1 \
--reward acc_reward \
--data_root /home/dataset/imagenet \
--ckpt_path /home/young/liuyixin/8.29/CAMC/checkpoints/resnet50-19c8e357.pth \
--seed 2020 --data_bsize 16 \
--n_gpu 1 --warmup 100 --rmsize 100 \
--train_episode 800 --suffix resnet50_100_800 \
--n_calibration_batches 5 \
--model_cached_ckp /home/young/liuyixin/8.29/CAMC/cached/_ckp.pth.tar
