python  main\\train.py \
    --model=mobilenet \
    --dataset=cifar10 \
    --lr=0.05 \
    --n_gpu=4 \
    --batch_size=256 \
    --n_worker=32 \
    --lr_type=cos \
    --n_epoch=100 \
    --wd=4e-5 \
    --seed=2020 \
    --data_root=/home/dataset/cifar